import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { CalendarDays, Plus, Trash2, Pencil, Users, Filter } from "lucide-react";
import { api } from "@/lib/api";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

const STATUSES=["Pending","Confirmed","Arrived","Completed","Cancelled","No Show"];
const blank={date:new Date().toISOString().slice(0,10),time:"18:00",guest_name:"",phone:"",pax:2,table_area:"",guide_name:"",travel_agent:"",package:"",status:"Pending",special_request:"",notes:""};
const monthNow=new Date().toISOString().slice(0,7);
function Kpi({label,value}){return <div className="rounded-xl p-4 border bg-white border-[#E5DECF]"><div className="text-[10px] uppercase tracking-[.18em] text-[#C9A227] font-bold">{label}</div><div className="font-display text-2xl font-bold mt-1">{value}</div></div>}
function ReservationForm({value,onChange,onClose,onSaved}){
 const set=(k,v)=>onChange({...value,[k]:v});
 return <div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><div className="bg-[#FAF8F5] rounded-2xl w-full max-w-3xl max-h-[92vh] overflow-auto p-6 border border-[#C9A227]">
  <div className="flex justify-between mb-5"><div><div className="text-xs uppercase tracking-[.2em] text-[#C9A227] font-bold">Reservation</div><h2 className="font-display text-3xl font-bold">{value.id?"Edit Reservation":"New Reservation"}</h2></div><button onClick={onClose}>✕</button></div>
  <div className="grid sm:grid-cols-2 gap-4">{[["date","Date","date"],["time","Time","time"],["guest_name","Guest Name","text"],["phone","WhatsApp","text"],["pax","Pax","number"],["table_area","Table / Area","text"],["guide_name","Guide","text"],["travel_agent","Travel Agent","text"],["package","Package / Menu","text"],["special_request","Special Request","text"],["notes","Notes","text"]].map(([k,l,t])=><div key={k}><Label>{l}</Label><Input className="mt-1" type={t} value={value[k]??""} onChange={e=>set(k,t==="number"?Number(e.target.value):e.target.value)}/></div>)}
  <div><Label>Status</Label><Select value={value.status} onValueChange={v=>set("status",v)}><SelectTrigger className="mt-1"><SelectValue/></SelectTrigger><SelectContent>{STATUSES.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select></div></div>
  <div className="flex justify-end gap-2 mt-6"><Button variant="outline" onClick={onClose}>Cancel</Button><Button className="bg-[#8B1A1A] text-white" onClick={async()=>{try{value.id?await api.updateReservation(value.id,value):await api.createReservation(value);toast.success("Reservation saved");onSaved();onClose()}catch(e){toast.error("Failed to save reservation")}}}>Save Reservation</Button></div>
 </div></div>
}
function Calendar({month,rows,onPick}){const [y,m]=month.split("-").map(Number); const first=new Date(y,m-1,1); const days=new Date(y,m,0).getDate(); const start=(first.getDay()+6)%7; const cells=Array(start).fill(null).concat(Array.from({length:days},(_,i)=>i+1)); const byDay={}; rows.forEach(r=>(byDay[r.date]??=[]).push(r)); return <div className="bg-white border border-[#E5DECF] rounded-xl overflow-hidden"><div className="grid grid-cols-7 text-center text-xs font-bold text-[#6E655F] bg-[#F1ECE3]">{["Mon","Tue","Wed","Thu","Fri","Sat","Sun"].map(d=><div className="p-3" key={d}>{d}</div>)}</div><div className="grid grid-cols-7">{cells.map((d,i)=>{if(!d)return <div key={i} className="min-h-28 border-t border-r border-[#EEE8DC]"/>;const key=`${month}-${String(d).padStart(2,"0")}`;return <button key={key} onClick={()=>onPick(key)} className="text-left min-h-28 p-2 border-t border-r border-[#EEE8DC] hover:bg-[#FAF3E2]"><div className="font-bold text-sm">{d}</div>{(byDay[key]||[]).slice(0,3).map(r=><div key={r.id} className="mt-1 text-[10px] rounded bg-[#8B1A1A] text-white px-1.5 py-1 truncate">{r.time} · {r.guest_name} ({r.pax})</div>)}{(byDay[key]||[]).length>3&&<div className="text-[10px] mt-1 text-[#8B1A1A]">+{byDay[key].length-3} more</div>}</button>})}</div></div>}
export default function Reservations(){const [month,setMonth]=useState(monthNow);const [rows,setRows]=useState([]);const [summary,setSummary]=useState(null);const [guide,setGuide]=useState("");const [ta,setTa]=useState("");const [form,setForm]=useState(null);const [tab,setTab]=useState("calendar");
 const load=async()=>{try{const [r,s]=await Promise.all([api.reservations(month,guide||undefined,ta||undefined),api.reservationSummary(month,guide||undefined,ta||undefined)]);setRows(r);setSummary(s)}catch{toast.error("Failed to load reservations")}};useEffect(()=>{load()},[month,guide,ta]);
 const edit=r=>setForm({...r}); const remove=async r=>{if(confirm(`Delete reservation for ${r.guest_name}?`)){await api.deleteReservation(r.id);load();toast.success("Reservation deleted")}};
 const guides=useMemo(()=>[...new Set(rows.map(r=>r.guide_name).filter(Boolean))],[rows]); const tas=useMemo(()=>[...new Set(rows.map(r=>r.travel_agent).filter(Boolean))],[rows]);
 return <div className="max-w-6xl mx-auto px-5 py-10"><div className="flex flex-col sm:flex-row justify-between gap-4 mb-7"><div><div className="text-xs uppercase tracking-[.25em] text-[#C9A227] font-bold mb-2">Guest Management</div><h1 className="font-display text-4xl font-bold">Reservations</h1><p className="text-[#6E655F] mt-2">Kelola booking, calendar, guide/travel agent, dan status tamu.</p></div><Button onClick={()=>setForm({...blank})} className="bg-[#8B1A1A] text-white rounded-full"><Plus className="w-4 h-4 mr-2"/> New Reservation</Button></div>
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-3 mb-6">{[["Reservations",summary?.totals?.reservations],["Pax",summary?.totals?.pax],["Confirmed",summary?.totals?.confirmed],["Completed",summary?.totals?.completed],["Cancelled",summary?.totals?.cancelled]].map(x=><Kpi key={x[0]} label={x[0]} value={x[1]??0}/>)}</div>
 <div className="flex flex-wrap gap-2 items-center mb-5"><Input type="month" value={month} onChange={e=>setMonth(e.target.value)} className="w-44"/><Select value={guide||"all"} onValueChange={v=>setGuide(v==="all"?"":v)}><SelectTrigger className="w-44"><Filter className="w-4 h-4 mr-2"/><SelectValue placeholder="Guide"/></SelectTrigger><SelectContent><SelectItem value="all">All Guides</SelectItem>{guides.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><Select value={ta||"all"} onValueChange={v=>setTa(v==="all"?"":v)}><SelectTrigger className="w-48"><SelectValue placeholder="Travel Agent"/></SelectTrigger><SelectContent><SelectItem value="all">All Travel Agents</SelectItem>{tas.map(x=><SelectItem key={x} value={x}>{x}</SelectItem>)}</SelectContent></Select><div className="ml-auto flex gap-2"><Button variant={tab==="calendar"?"default":"outline"} onClick={()=>setTab("calendar")}><CalendarDays className="w-4 h-4 mr-2"/>Calendar</Button><Button variant={tab==="list"?"default":"outline"} onClick={()=>setTab("list")}><Users className="w-4 h-4 mr-2"/>List</Button></div></div>
 {tab==="calendar"?<Calendar month={month} rows={rows} onPick={d=>setForm({...blank,date:d})}/>:<div className="bg-white rounded-xl border border-[#E5DECF] overflow-x-auto"><table className="w-full text-sm"><thead className="bg-[#F1ECE3]"><tr>{["Date","Time","Guest","Pax","Guide","Travel Agent","Status","Action"].map(x=><th key={x} className="text-left p-3">{x}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-[#EEE8DC]"><td className="p-3">{r.date}</td><td className="p-3">{r.time}</td><td className="p-3 font-semibold">{r.guest_name}<div className="text-xs text-[#6E655F]">{r.phone}</div></td><td className="p-3">{r.pax}</td><td className="p-3">{r.guide_name||"—"}</td><td className="p-3">{r.travel_agent||"—"}</td><td className="p-3"><span className="px-2 py-1 rounded-full bg-[#F1ECE3]">{r.status}</span></td><td className="p-3"><Button size="icon" variant="ghost" onClick={()=>edit(r)}><Pencil className="w-4 h-4"/></Button><Button size="icon" variant="ghost" onClick={()=>remove(r)}><Trash2 className="w-4 h-4"/></Button></td></tr>)}</tbody></table>{!rows.length&&<div className="p-10 text-center text-[#6E655F]">Belum ada reservasi untuk filter ini.</div>}</div>}
 <div className="grid md:grid-cols-2 gap-5 mt-7"><div className="bg-white border border-[#E5DECF] rounded-xl p-5"><h3 className="font-display text-xl font-bold mb-3">By Guide</h3>{(summary?.guides||[]).map(x=><div className="flex justify-between py-2 border-b last:border-0" key={x.name}><span>{x.name}</span><b>{x.reservations} res. / {x.pax} pax</b></div>)}</div><div className="bg-white border border-[#E5DECF] rounded-xl p-5"><h3 className="font-display text-xl font-bold mb-3">By Travel Agent</h3>{(summary?.travel_agents||[]).map(x=><div className="flex justify-between py-2 border-b last:border-0" key={x.name}><span>{x.name}</span><b>{x.reservations} res. / {x.pax} pax</b></div>)}</div></div>
 {form&&<ReservationForm value={form} onChange={setForm} onClose={()=>setForm(null)} onSaved={load}/>}</div>}
